### ISSUE TITLE
Omit issues that already have a PR up

### ISSUE THREAD

**Issue by danisyellis** [indeedeng/Mariner#100]
a PR can be attached to an issue. Mariner should check to make sure there isn't a PR attached to an issue before including the issue.

**Comment by kevindigo** [comment]
It looks like we should be able to easily do this by adding ` -linked:pr` into the search query string. 

If that doesn't work, we might need to run a second query for each repo, to obtain a list of open issues that are linked to PRs that will close them. The search string would be: `repo:${reponame} repo:${reponame2} is:open linked:pr` Our code would then need to omit issues found by the main query that are also returned by this second query.

**Comment by IngridGdesigns** [comment]
Testing revealed that this omits too many issues. Linking an issue to a PR doesn't necessarily mean that the PR actually has anything to do with solving that issue. The PR was closed for this.
