### ISSUE TITLE
Add badges to README.md

### ISSUE THREAD

**Issue by IngridGdesigns** [indeedeng/Mariner#104]
add additional[ shields.io](https://shields.io/) badges in the beginning of the ReadMe

Badges should be added for:
- license
- project language
- issues
- maintained

**example**: [starfish readme.md](https://github.com/indeedeng/starfish/blob/main/README.md)

If you have any ideas which badges might be interesting please feel free to add them

**Comment by Brolan14** [comment]
hi, i think i can help you out with this

**Comment by kevindigo** [comment]
Thanks for offering @Brolan14, but jk10274 has already put up a PR for this, which I think is about ready to get merged.
