### ISSUE TITLE
Switch to using the GraphQL API

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/Mariner#20]
Cross-repo querying using the GraphQL API will significantly improve the runtime of Mariner.

Sample Query:

```
query {
  search(query:"repo:facebook/react repo:mui-org/material-ui repo:elastic/elasticsearch label:\"good first issue\" created:>2020-07-06 state:open", type:ISSUE, first:100){
    issueCount
    edges{
      node{
        ... on Issue{
	  title
	  createdAt
          repository {
            nameWithOwner
          }
          url
    	}
      }
    }
  }
}
```

I have successfully tested the above query with up to 2000 repos listed in the query string. At some point above 2000 repos the API stops returning results.

The GraphQL API limits results to the first 100 items, and orders them in descending order by created date. A spot check of several queries showed less than 100 issues returned for 2000 repos within a given 3 month window. Given that, a reasonably safe approach would be to set a maximum repository count of 1000 repos per query. The end result should be a 1000x reduction in API calls (from 1 call per label per repo to 1 call per label per 1000 repos).

[Relevant Documentation For The Issue Object](https://docs.github.com/en/graphql/reference/objects#issue)

**Comment by DuaneOBrien** [comment]
We could effective close this one now couldn't we?

**Comment by kevindigo** [comment]
We still have some README improvements to do, but yes, all the coding is complete, so I'll close it as fixed.
