### ISSUE TITLE
Add pre-commit linting hooks

### ISSUE THREAD

**Issue by redgardner** [indeedeng/Mariner#54]
In order to catch issues earlier rather than later, pre-commit linting hooks using husky should be set up. Discussed on PR #51

**Comment by redgardner** [comment]
I went ahead and put a PR together for this. Hope that's okay.

**Comment by kevindigo** [comment]
@redgardner : It's absolutely OK that you jumped into this. I added the hacktoberfest label to this issue, and linked this issue to the PR. Hopefully that will be enough for you to get credit. (I still find all these combinations of labels to be a bit confusing.)
