### ISSUE TITLE
Add the ability to format the output as GitHub markdown

### ISSUE THREAD

**Issue by kevindigo** [indeedeng/Mariner#63]
Mariner should support a call to convert the existing output (JSON) into GitHub markdown. A rough draft of the code for this already exists here: https://github.com/indeedeng/Mariner-Issue-Collector/blob/main/Utilities/generateGitHubMarkdown.js

The code will need to be convert to TypeScript, and integrated similar to how we brought in the Confluence Wiki formatting in https://github.com/indeedeng/Mariner/pull/59 and https://github.com/indeedeng/Mariner/pull/60

**Comment by IngridGdesigns** [comment]
sorry, accidentally unassigned myself!
