### ISSUE TITLE
Confluence output function is misnamed

### ISSUE THREAD

**Issue by kevindigo** [indeedeng/Mariner#76]
When we added the `generateConfluenceMarkdown` function (and source file), we didn't realize that Confluence uses a markup language which is unrelated to Markdown. The function should be called `generateConfluenceMarkup`, and the containing source file should be named `generateConfluenceMarkup.ts`. 

We should continue to export the old function name as an alias, to be backward compatible with anyone who has already started calling it.

**Comment by IngridGdesigns** [comment]
the README.md should be updated too to include the alias and the `generateConfluenceMarkup`
